import React from "react";
import { FileText } from "lucide-react";

const MedicalReportTemplate = ({ reportData }) => {
  return (
    <div className="w-full max-w-4xl mx-auto bg-white p-8 shadow-sm border border-gray-200">
      {/* Header */}
      <div className="flex justify-between items-center border-b-2 border-blue-800 pb-4">
        <div className="flex items-center space-x-2">
          <h1 className="text-2xl text-blue-800 font-light">
            SKINLENS AI ANALYSIS REPORT
          </h1>
        </div>
        <div className="text-sm text-gray-600">
          <p>Report #: {reportData?.reportId || "AI-08-0013908"}</p>
        </div>
      </div>

      {/* Patient Information */}
      <div className="grid grid-cols-2 gap-x-8 gap-y-2 mt-4 text-sm">
        <div>
          <span className="font-semibold">Patient Name: </span>
          {reportData?.patientInfo?.name || "[Patient Name]"}
        </div>
        <div>
          <span className="font-semibold">Case #: </span>
          {reportData?.patientInfo?.caseNumber}
        </div>
        <div>
          <span className="font-semibold">DOB/Age/Sex: </span>
          {reportData?.patientInfo?.demographics}
        </div>
        <div>
          <span className="font-semibold">Analyzed: </span>
          {reportData?.analysisDate || new Date().toLocaleString()}
        </div>
        <div>
          <span className="font-semibold">Patient ID: </span>
          {reportData?.patientInfo?.patientId}
        </div>
        <div>
          <span className="font-semibold">Report Generated: </span>
          {reportData?.generatedDate || new Date().toLocaleString()}
        </div>
      </div>

      {/* Main Content */}
      <div className="mt-8 space-y-6">
        {/* AI Analysis */}
        <section>
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-2">
            AI Analysis
          </h2>
          <div className="pl-4">
            <p>
              {reportData?.analysis?.mainFindings ||
                "Analysis details will appear here"}
            </p>
            <p className="text-sm text-gray-600 mt-2">
              Confidence Level: {reportData?.analysis?.confidence || "95%"}
            </p>
          </div>
        </section>

        {/* Detailed Examination */}
        <section>
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-2">
            Detailed Examination
          </h2>
          <div className="pl-4 space-y-2">
            <p>
              <span className="font-medium">Location: </span>
              {reportData?.examination?.location}
            </p>
            <p>
              <span className="font-medium">Characteristics: </span>
              {reportData?.examination?.characteristics}
            </p>
            <p>
              <span className="font-medium">Additional Findings: </span>
              {reportData?.examination?.additionalFindings}
            </p>
          </div>
        </section>

        {/* Analysis Summary */}
        <section>
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-2">
            Analysis Summary
          </h2>
          <div className="pl-4">
            <p>
              <span className="font-medium">Primary Condition: </span>
              {reportData?.summary?.condition}
            </p>
            <p>
              <span className="font-medium">Severity: </span>
              {reportData?.summary?.severity}
            </p>
            <p className="mt-2">{reportData?.summary?.description}</p>
          </div>
        </section>

        {/* Recommendations */}
        <section>
          <h2 className="text-lg font-semibold border-b border-gray-300 pb-1 mb-2">
            Recommendations
          </h2>
          <div className="pl-4">
            <ul className="list-disc list-inside space-y-1">
              {reportData?.recommendations?.map((rec, index) => (
                <li key={index}>{rec}</li>
              )) || (
                <>
                  <li>Consult with a dermatologist for confirmation</li>
                  <li>Follow recommended skin care routine</li>
                  <li>Monitor for changes in condition</li>
                </>
              )}
            </ul>
          </div>
        </section>
      </div>

      {/* Footer */}
      <div className="mt-8 pt-4 border-t border-gray-300 text-sm text-gray-600">
        <p>This report was generated by SkinLens AI Analysis System</p>
        <p className="mt-1">
          DISCLAIMER: This AI-generated report is for informational purposes
          only and should not be considered a medical diagnosis. Please consult
          with a healthcare professional for proper medical advice.
        </p>
      </div>

      {/* Report Details */}
      <div className="mt-4 text-xs text-gray-500">
        <p>Report ID: {reportData?.reportId || "AI-08-0013908"}</p>
        <p>Generated on: {new Date().toLocaleString()}</p>
      </div>
    </div>
  );
};

export default MedicalReportTemplate;
